### PR TITLE
Adding API endpoints and classes

### PR DESCRIPTION
**Pull request by bryan-ente**
- added type declarations
- function documentation
- added better error return values

Would be nice, if this could've been merged

### CODE REVIEW

**Comment by artemlos** [comment]
@Ente Thanks for the PR! I will review it and get back.

**Comment by bryan-ente** [comment]
Hey @artemlos,

since I might use Cryptolens in the future more often, I created my own class.
Currently with nearly all "Key"-API endpoints supported not just only the activation.

Would be nice, if you could review it as it brings new features being a benefit for everyone.

**Comment by bryan-ente** [comment]
Merged your base file `Cryptolens_old.php` into fork main.
Commiting changes to patch-1 from now.

**Comment by bryan-ente** [comment]
I will close, as my recent changes are in #2

**Pull request closed without merging**
